### ISSUE TITLE
CSV - option to automatically infer headers

### ISSUE THREAD

**Issue by sergeysolovev** [denoland/std#3857] opened 2023-11-25 15:15 UTC
It would be amazing if this code worked, probably by passing something like `inferHeaders` option (suggested by @crowlKats).

```
import { stringify } from 'https://deno.land/std@0.208.0/csv/mod.ts';
const arr = [{ a: 1, b: 2 }, { a: 3, b: 4 }];
console.log(stringify(arr));
```

**Comment by sigmaSd** [comment] 2024-03-16 10:11
just want to mention that this works if you pass the columns options
```ts
console.log(stringify(arr, { columns: ["a", "b"] }));
```

without it it errors with
```
error: Uncaught (in promise) StringifyError: No property accessor function was provided for object
      throw new StringifyError(
```

**Comment by sergeysolovev** [comment] 2024-03-17 08:11
@sigmaSd thank you for the suggestion! It helped me to simplify my little wrapper to auto-stringify an array of objects

```
export class Csv {
  static stringify(array: Record<string, unknown>[]) {
    const columns = Object.keys(array[0]);
    return stringify(array, { columns }).trim();
  }
}
```

**Comment by iuioiua** [comment] 2024-03-18 22:45
I like this idea! Thoughts, @kt3k?

**Comment by sigmaSd** [comment] 2024-03-19 10:37
In the mean while, shouldn't `columns` property be mandatory instead of optional ? because currently it feels weird that if you just use `stringify(data)` it throws

**Comment by timreichen** [comment] 2024-03-19 15:07
Related: https://github.com/denoland/deno_std/issues/2660

**Comment by dandv** [comment] 2024-05-25 04:54
@iuioiua This is a feature request for auto-inferring headers, the way [mature CSV libraries do](https://csv.js.org/stringify/options/header/).

#2660 is an issue about marking the `columns` option as mandatory. If this feature (#3857) is implemented, then #2660 can be closed. Until then, #2660 can be resolved independently. We should reopen this issue (#3857).

**Comment by sergeysolovev** [comment] 2024-05-25 05:20
@dandv alright, ready

**Comment by timreichen** [comment] 2024-08-07 17:21
Strange that csv is now stable but these issues are not resolved yet.

**Comment by iuioiua** [comment] 2024-08-08 16:13
This is a feature request, not a bug. It can be added as a non-breaking change, so it's fine. Also, PRs are welcome.

**Closed** 2024-11-14 06:51 UTC
Labels: csv, PR welcome
